version: '3'
services:
  node_app:
    container_name: node_app
    restart: always
    build: .
    ports:
      - '4000:4000'
    links:
      - mongodb
    environment:
      # inform wait script to wait for mongodb
      WAIT_HOSTS: mongodb:27017
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      # copy data from local database over to the docker db
      - './data/db:/data/db'
